---
kind: pipeline
type: docker
name: edge-x86

clone:
  disable: true

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: alpinelinux/alpine-drone-ci:edge-x86
    commands:
      - linux32 build.sh
    environment:
      GH_TOKEN:
        from_secret: github_token
    pull: always

trigger:
  event:
    branch:
      - main
    event:
      - push
    # - pull_request

---
kind: pipeline
type: docker
name: edge-x86_64

clone:
  disable: true

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: alpinelinux/alpine-drone-ci:edge-x86_64
    commands:
      - build.sh
    environment:
      GH_TOKEN:
        from_secret: github_token
    pull: always

trigger:
  event:
    branch:
      - main
    event:
      - push
    # - pull_request

---
kind: pipeline
type: docker
name: edge-aarch64

clone:
  disable: true

platform:
  os: linux
  arch: arm64

steps:
  - name: build
    image: alpinelinux/alpine-drone-ci:edge-aarch64
    commands:
      - build.sh
    environment:
      GH_TOKEN:
        from_secret: github_token
    pull: always

trigger:
  event:
    branch:
      - main
    event:
      - push
    # - pull_request

---
kind: pipeline
type: docker
name: edge-armhf

clone:
  disable: true

platform:
  os: linux
  arch: arm

steps:
  - name: build
    image: alpinelinux/alpine-drone-ci:edge-armhf
    commands:
      - build.sh
    environment:
      GH_TOKEN:
        from_secret: github_token
    pull: always

trigger:
  event:
    branch:
      - main
    event:
      - push
    # - pull_request

---
kind: pipeline
type: docker
name: edge-armv7

clone:
  disable: true

platform:
  os: linux
  arch: arm

steps:
  - name: build
    image: alpinelinux/alpine-drone-ci:edge-armv7
    commands:
      - build.sh
    environment:
      GH_TOKEN:
        from_secret: github_token
    pull: always

trigger:
  event:
    branch:
      - main
    event:
      - push
    # - pull_request

